create table spree_products
(
    id integer default nextval('spree_products_id_seq'::regclass) not null primary key,
    name varchar default ''::character varying not null,
    description text,
    available_on timestamp,
    deleted_at timestamp,
    slug varchar,
    meta_description text,
    meta_keywords varchar,
    tax_category_id integer,
    shipping_category_id integer,
    created_at timestamp,
    updated_at timestamp,
    promotionable boolean default true,
    meta_title varchar,
    avg_rating numeric(7,5) default 0.0 not null,
    reviews_count integer default 0 not null,
    in_stock boolean default true,
    magerecord_product_entity_id integer,
    magerecord_product_id integer,
    bundled boolean default false,
    moq_limit integer default 0 not null,
    bin_category_id integer constraint fk_rails_c6eeed6ed5 references spree_bin_categories,
    crushable boolean default false,
    refundable boolean default true,
    cod_enabled boolean default true not null,
    loyalty_point numeric(20,4) default 0.0,
    availability_type integer default 1,
    depend_only_inventory_details boolean default false,
    electronic_product_code varchar,
    purchases_last_7_days integer default 0,
    purchases_last_7_days_updated_at timestamp,
    subscription_only boolean default false,
    loyalty_synced_at timestamp default CURRENT_TIMESTAMP,
    loyalty_sync_key varchar
);